services:
  - type: web
    name: cyclotron-cloud
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DROPBOX_ACCESS_TOKEN
        sync: false
      - key: ZAPIER_WEBHOOK_URL
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
    autoDeploy: true
